import type { ProductsResponse } from '$mct/types';

export const EXAMPLE_PRODUCTS_RESPONSE: ProductsResponse = {
  url: 'https://integrationtest.landc.co.uk/productdata/bestbuysMCT',
  body: '{"PropertyValue":250000,"RepaymentValue":125000,"PropertyType":1,"MortgageType":1,"InterestOnlyValue":0,"TermYears":25,"SchemePurpose":1,"SchemePeriods":[1,2,3,4],"SchemeTypes":[1,2],"NumberOfResults":100,"SortColumn":1}',
  result: {
    SummaryInfo: {
      LowestRate: 2.79,
      LowestPMT: 579.2,
      LowestAnnualCost: 7424,
      NumberOfLenders: 67,
      NumberOfProducts: 1504,
    },
    Products: [
      {
        ProductId: 635169,
        LenderId: 20,
        LenderName: 'Marsden',
        DirectToLender: false,
        ApplyDirectLink: '',
        LenderURL: 'https://assets.landc.co.uk/lender/marsden.gif',
        ProductSchemeFriendlyName: '3.70% discount to 31/07/27',
        Rate: 2.79,
        FollowOnRate: 'then 6.49% (variable)',
        PMT: 579.2,
        FutureValue: 117885.79,
        FutureMonthlyPayment: 823.37,
        TotalFees: 998,
        AnnualCost: 7449.4,
        ApplicationFee: 0,
        CompletionFee: 998,
        ValuationFee: 0,
        OtherFees: 0,
        Cashback: 0,
        BrokerFee: 0,
        OverpaymentLimit: '5% p/a',
        ERC: 'Early Repayment Charges apply',
        ERCText: '3% reducing to 2% until 31/07/27',
        ExitFee: 150,
        Legals: 'Payable',
        MinimumMortgageAmount: 30000,
        MaximumMortgageAmount: 2500000,
        LTV: 70,
        APR: 6.027,
        FollowOnRateValue: 6.49,
        SchemeLength: 24,
        SchemeTypeRefId: 53,
        IsRemortgage: false,
        RepresentativeExample:
          'A mortgage of £125,000.00 payable over 25 years, initially on a variable rate for 2 years at 2.79% and then on a variable rate of 6.49% for the remaining 23 years would require 24 payments of £579.20 and 276 payments of £823.37. The total amount payable would be £242,148.92 made up of the loan amount plus interest (£116,150.92) and fees (£998.00). The overall cost for comparison is 6.0% APRC representative.',
        SAP: 1,
        SharedOwnership: 'Not Available',
        NewBuild: 'Also Available for New Build',
        Offset: false,
        LtdCompany: '',
        HMO: false,
        Channel: 'Everyone',
        AvailableFor: 'Both',
      },
      {
        ProductId: 597886,
        LenderId: 20,
        LenderName: 'Marsden',
        DirectToLender: false,
        ApplyDirectLink: '',
        LenderURL: 'https://assets.landc.co.uk/lender/marsden.gif',
        ProductSchemeFriendlyName: '3.55% discount to 30/06/27',
        Rate: 2.94,
        FollowOnRate: 'then 6.49% (variable)',
        PMT: 588.87,
        FutureValue: 118022.52,
        FutureMonthlyPayment: 824.33,
        TotalFees: 998,
        AnnualCost: 7565.44,
        ApplicationFee: 0,
        CompletionFee: 998,
        ValuationFee: 0,
        OtherFees: 0,
        Cashback: 0,
        BrokerFee: 0,
        OverpaymentLimit: '5% p/a',
        ERC: 'Early Repayment Charges apply',
        ERCText: '3% reducing to 2% until 30/06/27',
        ExitFee: 150,
        Legals: 'Payable',
        MinimumMortgageAmount: 30000,
        MaximumMortgageAmount: 2500000,
        LTV: 80,
        APR: 6.046,
        FollowOnRateValue: 6.49,
        SchemeLength: 24,
        SchemeTypeRefId: 53,
        IsRemortgage: false,
        RepresentativeExample:
          'A mortgage of £125,000.00 payable over 25 years, initially on a variable rate for 2 years at 2.94% and then on a variable rate of 6.49% for the remaining 23 years would require 24 payments of £588.87 and 276 payments of £824.33. The total amount payable would be £242,645.96 made up of the loan amount plus interest (£116,647.96) and fees (£998.00). The overall cost for comparison is 6.0% APRC representative.',
        SAP: 1,
        SharedOwnership: 'Not Available',
        NewBuild: 'Also Available for New Build',
        Offset: false,
        LtdCompany: '',
        HMO: false,
        Channel: 'Everyone',
        AvailableFor: 'Both',
      },
      {
        ProductId: 636229,
        LenderId: 23,
        LenderName: 'Furness',
        DirectToLender: false,
        ApplyDirectLink: '',
        LenderURL: 'https://assets.landc.co.uk/lender/furness.gif',
        ProductSchemeFriendlyName: '3.81% discount for 2 years',
        Rate: 3,
        FollowOnRate: 'then 6.75% (variable)',
        PMT: 592.76,
        FutureValue: 118076.69,
        FutureMonthlyPayment: 843.55,
        TotalFees: 1054,
        AnnualCost: 7640.12,
        ApplicationFee: 0,
        CompletionFee: 999,
        ValuationFee: 305,
        OtherFees: 0,
        Cashback: 250,
        BrokerFee: 0,
        OverpaymentLimit: '10% p/a',
        ERC: 'Early Repayment Charges apply',
        ERCText: '2% for 2 years',
        ExitFee: 120,
        Legals: 'Payable',
        MinimumMortgageAmount: 30000,
        MaximumMortgageAmount: 2000000,
        LTV: 80,
        APR: 6.281,
        FollowOnRateValue: 6.75,
        SchemeLength: 24,
        SchemeTypeRefId: 53,
        IsRemortgage: false,
        RepresentativeExample:
          'A mortgage of £125,000.00 payable over 25 years, initially on a variable rate for 2 years at 3.00% and then on a variable rate of 6.75% for the remaining 23 years would require 24 payments of £592.76 and 276 payments of £843.55. The total amount payable would be £248,100.04 made up of the loan amount plus interest (£122,046.04) and fees (£1,054.00). The overall cost for comparison is 6.3% APRC representative.',
        SAP: 1,
        SharedOwnership: 'Not Available',
        NewBuild: 'Also Available for New Build',
        Offset: false,
        LtdCompany: '',
        HMO: false,
        Channel: 'Everyone',
        AvailableFor: 'Both',
      },
      {
        ProductId: 619700,
        LenderId: 23,
        LenderName: 'Furness',
        DirectToLender: false,
        ApplyDirectLink: '',
        LenderURL: 'https://assets.landc.co.uk/lender/furness.gif',
        ProductSchemeFriendlyName: '3.71% discount for 2 years',
        Rate: 3.04,
        FollowOnRate: 'then 6.75% (variable)',
        PMT: 595.37,
        FutureValue: 118112.63,
        FutureMonthlyPayment: 843.81,
        TotalFees: 1054,
        AnnualCost: 7671.44,
        ApplicationFee: 0,
        CompletionFee: 999,
        ValuationFee: 305,
        OtherFees: 0,
        Cashback: 250,
        BrokerFee: 0,
        OverpaymentLimit: '10% p/a',
        ERC: 'Early Repayment Charges apply',
        ERCText: '2% for 2 years',
        ExitFee: 120,
        Legals: 'Payable',
        MinimumMortgageAmount: 30000,
        MaximumMortgageAmount: 2000000,
        LTV: 80,
        APR: 6.286,
        FollowOnRateValue: 6.75,
        SchemeLength: 24,
        SchemeTypeRefId: 53,
        IsRemortgage: false,
        RepresentativeExample:
          'A mortgage of £125,000.00 payable over 25 years, initially on a variable rate for 2 years at 3.04% and then on a variable rate of 6.75% for the remaining 23 years would require 24 payments of £595.37 and 276 payments of £843.81. The total amount payable would be £248,234.44 made up of the loan amount plus interest (£122,180.44) and fees (£1,054.00). The overall cost for comparison is 6.3% APRC representative.',
        SAP: 1,
        SharedOwnership: 'Not Available',
        NewBuild: 'Also Available for New Build',
        Offset: false,
        LtdCompany: '',
        HMO: false,
        Channel: 'Everyone',
        AvailableFor: 'Both',
      },
    ],
  },
};
